deployment to prod namespace

diff --git a/.github/workflows/solar-system.yml b/.github/workflows/solar-system.yml
--- a/.github/workflows/solar-system.yml
+++ b/.github/workflows/solar-system.yml
@@ -338,30 +338,30 @@ jobs:
           done
           echo "ALB_HOST=$HOST" >> $GITHUB_OUTPUT
 
-  integration-testing:
-    name: Dev Integration Testing
-    if: contains(github.ref, 'feature/')
-    needs: dev-deploy
-    runs-on: ubuntu-latest
+  # integration-testing:
+  #   name: Dev Integration Testing
+  #   if: contains(github.ref, 'feature/')
+  #   needs: dev-deploy
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - name: Test `/live` Endpoint
-        env:
-           INGRESS_HOST: solar-system-dev.dominicsheytanya.org  
-        run: |
-          echo "Testing endpoint: http://$INGRESS_HOST/live"
+  #   steps:
+  #     - name: Test `/live` Endpoint
+  #       env:
+  #          INGRESS_HOST: solar-system-dev.dominicsheytanya.org  
+  #       run: |
+  #         echo "Testing endpoint: http://$INGRESS_HOST/live"
 
-           for i in {1..10}; do
-             if curl -sf http://$INGRESS_HOST/live; then
-               echo "Live endpoint is healthy"
-               exit 0
-             fi
-             echo " Waiting for /live endpoint..."
-             sleep 10
-          done
+  #          for i in {1..10}; do
+  #            if curl -sf http://$INGRESS_HOST/live; then
+  #              echo "Live endpoint is healthy"
+  #              exit 0
+  #            fi
+  #            echo " Waiting for /live endpoint..."
+  #            sleep 10
+  #         done
         
-          echo "Failed to reach /live endpoint at http://$INGRESS_HOST/live"
-          exit 1
+  #         echo "Failed to reach /live endpoint at http://$INGRESS_HOST/live"
+  #         exit 1
   
       
   prod-deploy:
