Deploy to kubernetes in dev namepace

diff --git a/.github/workflows/solar-system.yml b/.github/workflows/solar-system.yml
--- a/.github/workflows/solar-system.yml
+++ b/.github/workflows/solar-system.yml
@@ -9,7 +9,10 @@ on:
 
 permissions:
   id-token: write 
-  contents: write 
+  pull-requests: write
+  statuses: write
+  actions: read
+  contents: read
 
 env:
   MONGO_URI: ${{ secrets.MONGO_URI }}
@@ -110,7 +113,7 @@ jobs:
         env:  
           JF_URL: ${{ vars.JF_URL }}
           JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
-          
+
         #   # JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         # with:
         #   oidc-provider-name: github-jfrog-intragration 
@@ -229,4 +232,89 @@ jobs:
           push: true
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
 
-        #
+  dev-deploy:
+    runs-on: ubuntu-latest
+    needs: docker
+    outputs:
+      alb_host: ${{ steps.fetch-alb-host.outputs.alb_host }}
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
+      - name: Configure AWS Credentials with OIDC
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: ${{ secrets.CI_ROLE }}
+          aws-region: eu-north-1
+
+      - name: Install kubectl CLI
+        uses: azure/setup-kubectl@v3
+        with:
+           version: 'v1.26.0'
+
+      - name: Configure kubectl
+        run: aws eks --region eu-north-1 update-kubeconfig --name hr-dev-eks-cloud
+       
+      - name: Replace tokens in manifest files
+        uses: cschleiden/replace-tokens@v1
+        with:
+          tokenPrefix: '_'
+          tokenSuffix: '_'
+          files: kubernetes/development/*.yaml
+        env:
+          NAMESPACE: ${{ vars.NAMESPACE }}
+          REPLICAS: ${{ vars.REPLICAS }}
+          IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
+          # INGRESS_IP: ${{ env.INGRESS_IP }}
+
+      - name: Verify updated manifests
+        run: |
+          cat kubernetes/development/*.yaml
+
+      - name: Create MongoDB Secret
+        run: |
+          kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
+            --from-literal=MONGO_URI=${{ env.MONGO_URI }} \
+            --from-literal=MONGO_USERNAME=${{ env.MONGO_USERNAME }} \
+            --from-literal=MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
+            --save-config \
+            --dry-run=client \
+            -o yaml | kubectl apply -f -
+
+      - name: Deploy to Dev Environment
+        run: |
+          kubectl apply -f kubernetes/development
+
+      - name: Fetch ALB Host
+        id: fetch-alb-host
+        run: |
+          for i in {1..20}; do
+            HOST=$(kubectl get ingress my-app-ingress -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
+            if [ -n "$HOST" ]; then break; fi
+            echo "Waiting for ALB DNS..."
+            sleep 15
+          done
+          echo "alb-host=$HOST" >> $GITHUB_OUTPUT
+
+  # integration-testing:
+  #   name: Dev Integration Testing
+  #   needs: dev-deploy
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Test `/live` Endpoint
+  #       env:
+  #          INGRESS_HOST: ${{ needs.dev-deploy.outputs.alb_host }}
+  #       run: |
+  #         echo "Testing endpoint: http://$INGRESS_HOST/live"
+
+  #          for i in {1..10}; do
+  #            if curl -sf http://$INGRESS_HOST/live; then
+  #              echo "Live endpoint is healthy"
+  #              exit 0
+  #            fi
+  #            echo "⏳ Waiting for /live endpoint..."
+  #            sleep 10
+  #         done
+        
+  #         echo "Failed to reach /live endpoint at http://$INGRESS_HOST/live"
+  #         exit 1
