Deploy to dev environment

diff --git a/.github/workflows/solar-system.yml b/.github/workflows/solar-system.yml
--- a/.github/workflows/solar-system.yml
+++ b/.github/workflows/solar-system.yml
@@ -327,41 +327,41 @@ jobs:
         run: |
           kubectl apply -f kubernetes/development
 
-      # - name: Fetch ALB Host
-      #   id: fetch-alb-host
-      #   run: |
-      #     for i in {1..20}; do
-      #       HOST=$(kubectl -n dev get ingress solar-system -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
-      #       if [ -n "$HOST" ]; then break; fi
-      #       echo "Waiting for ALB DNS..."
-      #       sleep 15
-      #     done
-      #     echo "ALB_HOST=$HOST" >> $GITHUB_OUTPUT
+      - name: Fetch ALB Host
+        id: fetch-alb-host
+        run: |
+          for i in {1..20}; do
+            HOST=$(kubectl -n dev get ingress solar-system -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
+            if [ -n "$HOST" ]; then break; fi
+            echo "Waiting for ALB DNS..."
+            sleep 15
+          done
+          echo "ALB_HOST=$HOST" >> $GITHUB_OUTPUT
 
-  # integration-testing:
-  #   name: Dev Integration Testing
-  #   if: contains(github.ref, 'feature/')
-  #   needs: dev-deploy
-  #   runs-on: ubuntu-latest
+  integration-testing:
+    name: Dev Integration Testing
+    if: contains(github.ref, 'feature/')
+    needs: dev-deploy
+    runs-on: ubuntu-latest
 
-  #   steps:
-  #     - name: Test `/live` Endpoint
-  #       env:
-  #          INGRESS_HOST: solar-system-dev.dominicsheytanya.org  
-  #       run: |
-  #         echo "Testing endpoint: http://$INGRESS_HOST/live"
+    steps:
+      - name: Test `/live` Endpoint
+        env:
+           INGRESS_HOST: solar-system-dev.dominicsheytanya.org  
+        run: |
+          echo "Testing endpoint: http://$INGRESS_HOST/live"
 
-  #          for i in {1..10}; do
-  #            if curl -sf http://$INGRESS_HOST/live; then
-  #              echo "Live endpoint is healthy"
-  #              exit 0
-  #            fi
-  #            echo " Waiting for /live endpoint..."
-  #            sleep 10
-  #         done
+           for i in {1..10}; do
+             if curl -sf http://$INGRESS_HOST/live; then
+               echo "Live endpoint is healthy"
+               exit 0
+             fi
+             echo " Waiting for /live endpoint..."
+             sleep 10
+          done
         
-  #         echo "Failed to reach /live endpoint at http://$INGRESS_HOST/live"
-  #         exit 1
+          echo "Failed to reach /live endpoint at http://$INGRESS_HOST/live"
+          exit 1
   
       
   prod-deploy:
